// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cromberbus

import (
	"sync"
)

var (
	lockHandlerResolverMockResolve sync.RWMutex
)

// HandlerResolverMock is a mock implementation of HandlerResolver.
//
//     func TestSomethingThatUsesHandlerResolver(t *testing.T) {
//
//         // make and configure a mocked HandlerResolver
//         mockedHandlerResolver := &HandlerResolverMock{
//             ResolveFunc: func(command Command) (CommandHandler, error) {
// 	               panic("TODO: mock out the Resolve method")
//             },
//         }
//
//         // TODO: use mockedHandlerResolver in code that requires HandlerResolver
//         //       and then make assertions.
//
//     }
type HandlerResolverMock struct {
	// ResolveFunc mocks the Resolve method.
	ResolveFunc func(command Command) (CommandHandler, error)

	// calls tracks calls to the methods.
	calls struct {
		// Resolve holds details about calls to the Resolve method.
		Resolve []struct {
			// Command is the command argument value.
			Command Command
		}
	}
}

// Resolve calls ResolveFunc.
func (mock *HandlerResolverMock) Resolve(command Command) (CommandHandler, error) {
	if mock.ResolveFunc == nil {
		panic("HandlerResolverMock.ResolveFunc: method is nil but HandlerResolver.Resolve was just called")
	}
	callInfo := struct {
		Command Command
	}{
		Command: command,
	}
	lockHandlerResolverMockResolve.Lock()
	mock.calls.Resolve = append(mock.calls.Resolve, callInfo)
	lockHandlerResolverMockResolve.Unlock()
	return mock.ResolveFunc(command)
}

// ResolveCalls gets all the calls that were made to Resolve.
// Check the length with:
//     len(mockedHandlerResolver.ResolveCalls())
func (mock *HandlerResolverMock) ResolveCalls() []struct {
	Command Command
} {
	var calls []struct {
		Command Command
	}
	lockHandlerResolverMockResolve.RLock()
	calls = mock.calls.Resolve
	lockHandlerResolverMockResolve.RUnlock()
	return calls
}
